import { EventPublisher } from './event-publisher';
import { MesEvent } from './types/event-publisher.type';

/**
 * Interface representing a Protobuf message type generated by ts-proto.
 */
export interface ProtoMessage<T> {
  encode(message: T, writer?: any): any;
  decode(input: Uint8Array, length?: number): T;
  create(base?: Partial<T>): T;
}

export class TypedEventPublisher {
  constructor(
    private publisher: EventPublisher,
    private envelopeProto: ProtoMessage<MesEvent<any>> // The compiled MesEvent protobuf class
  ) {}

  /**
   * Publishes a typed domain event wrapped in the standard MesEvent envelope.
   */
  async publishEvent<T>(
    topic: string,
    key: string,
    eventParams: Omit<MesEvent<T>, 'data'>,
    payloadData: T,
    payloadProto: ProtoMessage<T>
  ): Promise<void> {
    // 1. Encode the specific domain payload (e.g., ProductCreatedPayload)
    const encodedPayload = payloadProto.encode(payloadProto.create(payloadData)).finish();

    // 2. Wrap the payload in the Envelope
    const envelope = this.envelopeProto.create({
      ...eventParams,
      data: encodedPayload,
    });

    // 3. Encode the envelope itself
    const envelopeBuffer = Buffer.from(this.envelopeProto.encode(envelope).finish());

    // 4. Send via Kafka (EventPublisher expects Buffer | string)
    this.publisher.publish({
      topic,
      key,
      data: envelopeBuffer,
    });
  }
}
